### ISSUE TITLE
Could not find a version that satisfies the requirement json (from -r requirements.txt (line 6))

### ISSUE THREAD

**Issue by ghost** [Warflop/Whoisleak#1]
Hi 
When installing requirements.txt it gives this error

Could not find a version that satisfies the requirement json (from -r requirements.txt (line 6)) (from versions: ) No matching distribution found for json (from -r requirements.txt (line 6))

Thanks!
p.s i installed nodejs-legacy

**Comment by Warflop** [comment]
Json requirement is installed by default but i'll update now the list.

Thank's for your review.

**Comment by Sydwicked** [comment]
> Hi
> When installing requirements.txt it gives this error
> 
> Could not find a version that satisfies the requirement json (from -r requirements.txt (line 6)) (from versions: ) No matching distribution found for json (from -r requirements.txt (line 6))

Same error on line 7 for the package time

**Comment by Warflop** [comment]
> > Hi
> > When installing requirements.txt it gives this error
> > Could not find a version that satisfies the requirement json (from -r requirements.txt (line 6)) (from versions: ) No matching distribution found for json (from -r requirements.txt (line 6))
> 
> Same error on line 7 for the package time

"time" requirement is installed by default but i'll update now the list.

Thank's for your review.
